baseURL = "https://blog.jan-steinke.de/"
languageCode = "de-de"
title = "Eine weitere Selbstdarstellung"
theme = "ananke"
DefaultContentLanguage = "de"
copyright = "alles meins"

[languages]
  [languages.en]
    title = "Just another grandstanding"
    weight = 1
    baseURL = "https://blog.jan-steinke.de/en"
    copyright = "Everything is mine"
  [languages.de]
    title = "Eine weitere Selbstdarstellung"
    weight = 2
    baseURL = "https://blog.jan-steinke.de/"
