baseURL = "https://blog.jan-steinke.de/"
languageCode = "en-us"
title = "Just another grandstanding"
theme = "ananke"
DefaultContentLanguage = "en"
copyright = "Everything is mine"

[languages]
  [languages.en]
    title = "Just another grandstanding"
    weight = 1
  [languages.de]
    title = "Eine weitere Selbstdarstellung"
    weight = 2
