baseURL = "https://blog.jan-steinke.de"
languageCode = "de-de"
title = "Eine weitere Selbstdarstellung"
theme = [ "github.com/jan-xyz/hugo-module-img-srcset", "github.com/theNewDynamic/gohugo-theme-ananke"]
DefaultContentLanguage = "de"
timeout = "120s"

[pagination]
pagerSize = 9

[module]
[[module.imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'

[params]
  site_logo = "/img/logo.svg"
  show_reading_time = true
  [[params.ananke_socials]]
  name = "twitter"
  url = "https://twitter.com/janxyz"
  [[params.ananke_socials]]
  name = "github"
  url = "https://github.com/jan-xyz"
  [[params.ananke_socials]]
  name = "mastodon"
  url = "https://det.social/@janxyz"
  rel = "me"
  [[params.ananke_socials]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/jan-steinke-b5b3a346/"

[languages]
  [languages.de]
    title = "Eine weitere Selbstdarstellung"
    weight = 1
    copyright = "alles meins"
    languageName = "Deutsch"
    [[languages.de.menu.main]]
    url    = "/de/"
    name   = "Startseite"
    weight = 10
    [[languages.de.menu.main]]
    url    = "/posts/tech/"
    name   = "Tech"
    weight = 12
  [languages.en]
    title = "Just another grandstanding"
    weight = 2
    copyright = "Everything is mine"
    languageName = "English"
    [[languages.en.menu.main]]
    url    = "/en/"
    name   = "Home"
    weight = 10
    [[languages.en.menu.main]]
    url    = "/en/posts/tech/"
    name   = "Tech"
    weight = 12
