baseURL = "https://blog.jan-steinke.de"
languageCode = "de-de"
title = "Eine weitere Selbstdarstellung"
theme = "ananke"
DefaultContentLanguage = "de"
copyright = "alles meins"
sectionPagesMenu = "main"
Paginate = 9

[params]
  twitter = "https://twitter.com/janxyz"
  github = "https://github.com/jan-xyz"
  facebook = "http://facebook.com/jan.steinke"

[languages]
  [languages.de]
    title = "Eine weitere Selbstdarstellung"
    weight = 1
    languageName = "Deutsch"
  [languages.en]
    title = "Just another grandstanding"
    weight = 2
    copyright = "Everything is mine"
    languageName = "English"
