baseURL = "https://blog.jan-steinke.de"
languageCode = "de-de"
title = "Eine weitere Selbstdarstellung"
theme = [ "github.com/jan-xyz/hugo-module-img-srcset", "github.com/jan-xyz/gohugo-theme-ananke"]
DefaultContentLanguage = "de"
Paginate = 9
timeout = "120s"

[params]
  twitter = "https://twitter.com/janxyz"
  github = "https://github.com/jan-xyz"
  site_logo = "/img/logo.svg"
  show_reading_time = true

[languages]
  [languages.de]
    title = "Eine weitere Selbstdarstellung"
    weight = 1
    copyright = "alles meins"
    languageName = "Deutsch"
    [[languages.de.menu.main]]
    url    = "/de/"
    name   = "Startseite"
    weight = 10
    [[languages.de.menu.main]]
    url    = "/posts/travel/"
    name   = "Reisen"
    weight = 11
    [[languages.de.menu.main]]
    url    = "/posts/tech/"
    name   = "Tech"
    weight = 12
  [languages.en]
    title = "Just another grandstanding"
    weight = 2
    copyright = "Everything is mine"
    languageName = "English"
    [[languages.en.menu.main]]
    url    = "/en/"
    name   = "Home"
    weight = 10
    [[languages.en.menu.main]]
    url    = "/en/posts/travel/"
    name   = "Travel"
    weight = 11
    [[languages.en.menu.main]]
    url    = "/en/posts/tech/"
    name   = "Tech"
    weight = 12
