baseURL = "https://blog.jan-steinke.de"
languageCode = "de-de"
title = "Eine weitere Selbstdarstellung"
theme = "gohugo-theme-ananke"
DefaultContentLanguage = "de"
sectionPagesMenu = "main"
Paginate = 9

[params]
  twitter = "https://twitter.com/janxyz"
  github = "https://github.com/jan-xyz"
  facebook = "http://facebook.com/jan.steinke"

[languages]
  [languages.de]
    title = "Eine weitere Selbstdarstellung"
    weight = 1
    copyright = "alles meins"
    languageName = "Deutsch"
    [[languages.de.menu.main]]
    url    = "/de/"
    name   = "Home"
    weight = 0
  [languages.en]
    title = "Just another grandstanding"
    weight = 2
    copyright = "Everything is mine"
    languageName = "English"
    [[languages.en.menu.main]]
    url    = "/en/"
    name   = "Home"
    weight = 0
