[build]
publish = "public"
command = "hugo --gc --minify"

[build.environment]
GO_VERSION = "1.16"
HUGO_VERSION = "0.83.1"

[context.production.environment]
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
