[build]
publish = "public"
command = "hugo --gc --minify"

[build.environment]
GO_VERSION = "1.23"
HUGO_VERSION = "0.134.0"

[context.production.environment]
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
