[build]
publish = "public"
command = "hugo --gc --minify"

[build.environment]
GO_VERSION = "1.24"
HUGO_VERSION = "0.147.1"

[context.production.environment]
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
