[build]
publish = "public"
command = "hugo --gc --minify"

[build.environment]
GO_VERSION = "1.15"
HUGO_VERSION = "0.78.2"

[context.production.environment]
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
