[build]
publish = "public"
command = "hugo --gc --minify"

[build.environment]
GO_VERSION = "1.17"
HUGO_VERSION = "0.93.3"

[context.production.environment]
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
